import type { Metadata } from "next";

import { firaSans } from "@/fonts";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${firaSans.className} antialiased  min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
